### ISSUE TITLE
Material example throws undefined

### ISSUE THREAD

**Issue by Bojhan** [prescottprue/redux-firebasev3#12]
I tried installing the new example.

It looks like the material example throws
`connect.js:117 Uncaught TypeError: Cannot read property 'firebase' of undefined`

After running npm install and npm start. I ran a few debugging rounds, but have yet to find the error.

**Comment by prescottprue** [comment]
@Bojhan I am looking into it now. Thank you for pointing it out!

There will be a bunch more updates coming to those examples this weekend.

**Comment by Bojhan** [comment]
It looks like its a routing related problem, trying to debug. 

Its caused by an undefined firebase with no property in src/containers/App/App.js

```
@firebase()
```

I did a small fix by moving router.js into index.js and loading firebase - but that doesnt seem quite right.

**Comment by prescottprue** [comment]
@Bojhan I believe I have a fix for it, but am still testing things. Will hopefully be posting the fix today or tomorrow.

**Comment by prescottprue** [comment]
@Bojhan It is running on my end once again, give it a try and let me know, and I will leave the issue open in the meantime.

I am also planning on updating the example to include Google Login.

**Comment by Bojhan** [comment]
Thanks, yup that worked! 

Do wish to note that some peer dependancies are not installed by default. 

```
npm WARN react-tap-event-plugin@1.0.0 requires a peer of react@^15.0.0-0 but none was installed.
npm WARN redux-firebasev3@0.1.2 requires a peer of react-redux@^4.0.6 but none was installed.
npm WARN material-ui@0.15.4 requires a peer of react@^15.0.0 but none was installed.
npm WARN material-ui@0.15.4 requires a peer of react-dom@^15.0.0 but none was installed.
npm WARN react-addons-transition-group@15.3.1 requires a peer of react@^15.3.1 but none was installed.
npm WARN react-addons-create-fragment@15.3.1 requires a peer of react@^15.3.1 but none was installed.
```
