### ISSUE TITLE
Add PathDoesExists Helper

### ISSUE THREAD

**Issue by Bojhan** [prescottprue/redux-firebasev3#15]
Would be useful to add the following helper

https://gist.github.com/anantn/4323949

Which we could easily add to for example:

firebase.doesnotexist.set()

**Comment by prescottprue** [comment]
Would this be for other types of sets? Or do you mean specific to user data?

**Comment by Bojhan** [comment]
It would probably useful for any type of set? 

I imagine anytime you have a path that is unique. You would want to avoid overwriting it. Users is just one of those cases.

**Comment by prescottprue** [comment]
Looking into this for `v0.1.4` or `v0.1.5`

**Comment by prescottprue** [comment]
Added a helper named `uniqueSet` that contains this functionality. Just like all of the other helpers it returns a Promise as well as callback functionality.

The changes will be part of `v0.1.5` and will be released soon. If you want to seem the changes before they are merged, they are on [the `v0.1.5` branch](https://github.com/prescottprue/redux-firebasev3/tree/v0.1.5). Let me know if this does not provide the functionality you were asking for.

**Comment by prescottprue** [comment]
Changes included in [`v0.1.5` release](https://github.com/prescottprue/redux-firebasev3/releases/tag/v0.1.5).
