### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by mrshll** [prescottprue/redux-firebasev3#16]
I was able to do some drop in testing to my existing apps that used a redux-react-firebase fork adapted to v3 and everything seems to be working splendidly. It even fixed some intermittent react-native Release build babel issues so... !

You can close this immediately, just wanted to share some good news ;)

**Comment by prescottprue** [comment]
Awesome! Love all the work you have been doing @mmoutenot.

I will look into copying over those tests, but feel free to create a PR with them in there if you have already gotten them working.
