### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by brandonmikeska** [prescottprue/redux-firebasev3#2]
Hey do you have an example hooking this up with the chrome dev tools and react-router-redux. I have been trying and I can't get it to work. Any help would be awesome!

**Comment by prescottprue** [comment]
@brandonmikeska Are you sure you set up the reducer as showing in the README?

[This example](https://github.com/prescottprue/generator-react-firebase/tree/master/examples/react-firebase-redux) is the output of [generator-react-firebase](https://github.com/prescottprue/generator-react-firebase) and it works with redux dev tools on my computer:

![screen shot 2016-07-28 at 9 55 24 am](https://cloud.githubusercontent.com/assets/2992224/17222357/b42e251e-54ac-11e6-9ae5-61dec49fcf62.png)

Reached out by email too, so we can figure it out.

**Comment by brandonmikeska** [comment]
This helped me get up and working. Thanks a ton!
