### ISSUE TITLE
API documentation passing nesting with connect from redux incorrect?

### ISSUE THREAD

**Issue by Bojhan** [prescottprue/redux-firebasev3#20]
Using params to pass the ID

``` @firebase(
  props => {
    console.log('props.params.OrganisationID: ', props.params.OrganisationID)
    return [
     `Organistions/${props.params.OrganisationID}`
    ]
  }
)

@connect(
  (state, props) => {
    return {
     organisation: dataToJS(state.firebase, `Organisations/${props.params.OrganisationID}`),
   }
  }
)
```

This keeps returning no object, while something such as 

```
@firebase(['Organisations/NameOfThing'])
@connect(
  ({firebase}) => ({
    organisation: dataToJS(firebase, 'Organisations/NameOfThing'),
  })
)
```

Does return an object.

I am wondering if there any examples where you pass a param, because it looks like dataToJS doesn't work on state.firebase as it doesn't fill `organisation` with an object. 

Some additional context I am passing it like this:

`<Route path='/Organisation/:OrganisationID' component={Organisation} />`

`<Link to={`/Organisations/${id}`}>Edit</Link>`

**Comment by prescottprue** [comment]
The string with the id variable should work unless that variable is coming in as undefined or something similar. Going to try this in the example and post updates.

**Comment by Bojhan** [comment]
Ah, yup. I just found out what the issue was. 

This works great when your passing it from one page to the next. But it doesn't continue updating, since its set in the state.

**Comment by Bojhan** [comment]
Marking this closed, might be useful to add a example where its still continuously updates.

**Comment by prescottprue** [comment]
@Bojhan Great note. Will add the example soon.
