### ISSUE TITLE
Object.assign breaks immutable object.

### ISSUE THREAD

**Issue by mrshll** [prescottprue/redux-firebasev3#23]
Unfortunately, I think c00876211e892d1275f1ab29e0a1f704f0e0935b breaks things.

by using `Object.assign`, you destroy Immutable's prototype.

```
    case _constants.AUTHENTICATION_INIT_STARTED:
      return Object.assign({}, state, { isLoading: true });

    case _constants.AUTHENTICATION_INIT_FINISHED:
      return Object.assign({}, state, { isLoading: false });
```

**Comment by prescottprue** [comment]
This is fixed on my `v0.1.4` branch, and is working with the examples. Will be releasing either tonight or tomorrow.
