### ISSUE TITLE
Invalid keypath error Due to Snapshot Storage in ImmutableJS

### ISSUE THREAD

**Issue by mutewinter** [prescottprue/redux-firebasev3#28]
The `SET` action stores the `snapshot` from Firebase using `fromJS` [here](https://github.com/prescottprue/redux-firebasev3/blob/master/source/reducer.js#L42-L44).

Converting the Firebase snapshot to JS should at least involve `snapshot.val()`, to get an actual JS object.

Removing this code fixes the "Invalid keypath error" I'm getting when unmounting components.

But I'm puzzled why the snapshot is even being stored in the state? Perhaps so a user could access it directly?

**Comment by prescottprue** [comment]
@mutewinter Thanks for reporting! You are correct about why snapshot is stored, and I actually just encountered this bug myself last night.

Investigating a better way to store the snapshot in the longer term, but `v0.1.5` will not throw the warning. Totally open to suggestions or pull request on this front. Going to leave the issue open until `v0.1.5` is released with the error handled, but should be within the next day or two.

**Comment by prescottprue** [comment]
Changes included in [`v0.1.5` release](https://github.com/prescottprue/redux-firebasev3/releases/tag/v0.1.5).
