### ISSUE TITLE
Listening to user auth data.

### ISSUE THREAD

**Issue by yok0** [prescottprue/redux-firebasev3#30]
I cant seem to figure out how to access data stored in store under firebase>auth after user logs in.
I basically try to replace login form with currently logged in user email address.
Looping through this.props with Object.keys seems cumbersome. 
Is there any better way ?
Help much appreciated.

**Comment by Bojhan** [comment]
You shouldn't need to find it under firebase>auth. 

If you load in the data correctly (see material example) 

In Store.JS you change the middleware, if you follow the material example:
`reduxReactFirebase(fbConfig, { userProfile: 'users' }),` 
Replace users with however you call your users database object

Then you can just connect to get the account info - add it to PropTypes
`@firebase()
@connect(
  ({firebase}) => ({
    account: pathToJS(firebase, 'profile')
  })
)`

Then you can use it  `profile={this.props.account}`

Just make sure you do isLoaded and isEmpty before rendering it or you will get an undefined as it takes a few to load. 

What I am not sure about yet - is how to do it on the root route level and always just redirect to login when user is not logged in.

**Comment by hydr4n7** [comment]
Great stuff. Thanks a lot. One last thing. How can I wait till the profile is loaded.
When using `isLoaded` my form flashes for a  split of a second then the email address appears.
How would I go about removing that content flashing effect.

**Comment by yok0** [comment]
Thanks a lot.

Consider it as closed
