### ISSUE TITLE
Easy Population type function

### ISSUE THREAD

**Issue by Bojhan** [prescottprue/redux-firebasev3#33]
Just an idea, for a function that might make it a lot easier to retrieve references from other objects. For example if you are restricting your todo list per user.

http://mongoosejs.com/docs/populate.html

It's super useful in the MongoDB space, I haven't really seen it in firebase libraries.

**Comment by prescottprue** [comment]
@Bojhan I really love this idea, and actually worked with a library that a friend made a while back that included similar functionality.

I would be interested to see how the API would look for this. My initial thoughts are just to follow the same pattern with a `populate()` method, but I am not sure how it would work under the hood with redux (would probably need to use something like [normalizr](https://github.com/paularmstrong/normalizr).

**Comment by prescottprue** [comment]
I got a simple implementation of this working, looking like this to populate a list of projects that `collaborators` that is a list of user ids:

```
projects#populate=collaborators:users
```

It currently doesn't work right due to #38, so going to solve that first before trying to integrate this.

**Comment by prescottprue** [comment]
@Bojhan [`1.0.0` release](https://github.com/prescottprue/redux-firebasev3/releases/tag/v1.0.0) includes population capabilities. The docs include some basic examples, but the will soon be built out more.

**Note:** The library has been renamed to [react-redux-firebase](https://github.com/prescottprue/react-redux-firebase) for clarity and to match other redux library naming conventions.
