### ISSUE TITLE
Best way to retrieve data and using this as key for retrieving another dataset (without passing down state)

### ISSUE THREAD

**Issue by Bojhan** [prescottprue/redux-firebasev3#34]
Hi, 

I've been following the examples creating my App. 

However I've stumbled upon something quite hard to resolve, I am wondering if there is a better way. The current examples material and simple, depend on the idea of passing the state to the component.

``` @connect(
  state => ({
    currentTodo: state.myStore.currentTodo,
    todo: dataToJS(state.firebase, `todos/${state.myStore.currentTodo}`)
  })
)
@firebase(
  props => ([
    `todos/${props.currentTodo}`
  ])
)
```

However ideally you want your components to be independent, possibly being the entry point to your App. Say for example you have an account data set with an organisation object, and a organisation object separate. If you want to tie that together you have to make an unwieldy set of connects.  

Example of this:

```
// subscribe component to changes in profile
@firebase(
 props => ([
   `profile`
 ])
) 
// use this profile to fill account property
@connect(
 ({firebase}) => ({
   account: pathToJS(firebase, 'profile')
 })
)
// subscribe component to changes in specific organisation (if account is loaded)
@firebase(
 props => {
  if (props.account && props.account.organisation) {
   return [`Organisations/${props.account.organisation.name}`];
  } else {
    return [];
  }
 }
)
// create organisation property that's updated when organisation changes
@connect(
 ({firebase}, {account}) => ({
   organisation: account.organisation? dataToJS(firebase, `Organisations/${account.organisation.name}`) : {}
 })
)
```

This doesn't quite work. As organisation.name is undefined, until retrieved making the async part throw errors. 

The only other method I've seen is doing something along the lines of:

`{React.cloneElement(this.props.children, { account: this.state.account })}`

In the App.js. However this is rather hacky and has quite some side-effects or nest all in routes. 

Whats the best way to approach this leveraging this library?

**Comment by prescottprue** [comment]
1. You shouldn't need to provide this part:

``` js
@firebase(
 props => ([
   `profile`
 ])
) 
```

to sync profile. Notice how it is `pathToJS` instead of `dataToJS` which is used when loading data from any other location on firebase (profile/account is a built in "path"). AuthError is another "path" that is available for binding without needing to provide something to the list of listening locations within `@firebase()`.
1. The Account binding is auto enabled/disabled under the hood based in whether or not you are logged in. So do add account to your component/container just use:

``` js
// redux/firebase
import { connect } from 'react-redux'
import { firebase, helpers } from 'redux-firebasev3'
const { pathToJS } = helpers

@firebase()
@connect(
  // Map state to props
  ({firebase}) => ({
    authError: pathToJS(firebase, 'authError'),
    profile: pathToJS(firebase, 'profile')
  })
)
```

Does that make sense and answer what you were asking? [The Login container in the material example](https://github.com/prescottprue/redux-firebasev3/blob/master/examples/material/src/containers/Login/Login.js#L14-L25) is a good reference, but hoping to add another few examples soon.

**Comment by Bojhan** [comment]
Thanks! 

The issue I am faced with still exists, and the tricks shown above seem to run against a limitation that is not useful. 

If we imagine the following Firebase structure:

```
Users 
- Bojhan
-- Organisations
--- Somers

Organisations
- Somers
- Jansen

```

The best way to retrieve only the relevant Organisations for when your logged in as Bojhan. Would be to retrieve only`Organisations/Somers` using the $key organisation thats associated with the user`Users/Bojhan/Organisation/Somers` .

The material example requires passing down as props in the component, this makes it that a component is not independent. Additionally results in a lot of nesting. 

A potentially "clean" way is to pass props to the route path. However I am not sure if its possible to retrieve this data outside of a component. Either way this chaining challenge seems bound to happen once you get into creating more complex apps.

**Comment by Bojhan** [comment]
I ended up passing it in the route as `orgs` and doing something along the lines of:

```

@firebase(({ orgs= [] }) => (
  Object.keys(orgs).map(key => '/Organisations/' + key)
))

@connect(
  (state, props) => {
    return {
      organisations: dataToJS(state.firebase, `/Organisations`),
  };
 }
)
```

Not sure if its the best, but only way to work with props. Does require an additional nested level in the route to retrieve the orgs.

**Comment by prescottprue** [comment]
@Bojhan To combat this I have loaded account in higher components and passed it down as a prop, so it is available to lower components (which is where I place the logic to load the parts that depend on account). Not sure it solves what you mean, but going to get together an example this weekend to show what I mean.

On this note though, I was thinking about trying to include a helper method that would allow waiting for auth or other props to resolve before happening. Feel free to hop on the [redux-firebase Gitter](https://gitter.im/redux-firebase/Lobby?utm_source=share-link&utm_medium=link&utm_campaign=share-link) if you want to talk implementation.

**Comment by Bojhan** [comment]
This solves what I mean. its a bit of nesting - but looks pretty clean. 

Populate and having a nice loader on account resolved my other issues around this.
