### ISSUE TITLE
Custom Token Auth: Cannot read property 'email' of undefined

### ISSUE THREAD

**Issue by mutewinter** [prescottprue/redux-firebasev3#35]
Custom auth logins don't have a `user` entry for `userData`. [This code in redux-firebasev3](https://github.com/prescottprue/redux-firebasev3/blob/master/source/actions/auth.js#L198) causes an error because `user` is undefined.

I've got [my own fork of redux-firebasev3](https://github.com/prescottprue/redux-firebasev3/compare/master...mutewinter:feat-custom-token-support) and I added support for this case. I also added automatic JWT decoding with extraction of the extra fields for storage when creating the user.

The JWT decoding and storage might be too far, but it shouldn't just error out.

Thanks again for the library! So great.

**Comment by prescottprue** [comment]
@mutewinter Right you are, good catch! Looking at your fork now. I don't think those options are too much at all, especially if we eventually work in options to turn them on and off.

Are you interested in creating a pull request so I can merge your changes directly? If not, I can try combining them by hand later.

**Comment by mutewinter** [comment]
I've made even more updates since posting this. I will PR the changes that feel generic enough to be in this library. One change I made was to allow the user to pass a function for the `userProfile` location. I'm bucketing my data on a per-team basis (which is encoded into the user ID).

**Comment by prescottprue** [comment]
Included in [`v0.1.6` release](https://github.com/prescottprue/redux-firebasev3/releases/tag/v0.1.6).
