### ISSUE TITLE
Connect handler is only called on mount 

### ISSUE THREAD

**Issue by Bojhan** [prescottprue/redux-firebasev3#38]
The firebase connect handler (the function you can give to the firebase decorator) is only called
[on mount](https://github.com/prescottprue/redux-firebasev3/blob/master/source/connect.js#L76).

This means that when we use props to determine subscriptions, those can't be updated during the lifetime of the component. 

`Index.js`

``` js
@firebase(
 props => {
   const org = props.route.account.organisation.name
   return [
     `Organisations/${org}/somelist`
   ];
 }
)

@connect(
  (state, props) => {
    const org = props.route.account.organisation.name
    return {
      somelist: dataToJS(state.firebase, `Organisations/${org}/somelist`)
    };
 }
)
export default App({ somelist }) {
  return (
    <List list={somelist}/>
  )
}
```

`List.js`

``` js
@firebase({ list = [] } => (
  Object.keys(list).map(key => '/somelist/' + key)
)

@connect(
  (state) => ({
        experiments: dataToJS(state.firebase, `/somelist`),
  })
)
```

This is causing my problem in #34. Credits to @peteruithoven for helping figure this out.

**Comment by prescottprue** [comment]
@Bojhan Aware of this, and am working in a `componenWillRecieveProps` piece that should make it into one of the next few versions. I found this to be particularly necessary when designing functionality for `populate`.

**Comment by Bojhan** [comment]
Great! I was already expecting someone else would run into this, as anything where your chaining values this is an issue. 

Looking forward to seeing it 👍

**Comment by prescottprue** [comment]
@Bojhan [`1.0.0` release](https://github.com/prescottprue/redux-firebasev3/releases/tag/v1.0.0) includes handling of props changing. There will soon be an example of this in the new repo.

**Note:** The library has been renamed to [react-redux-firebase](https://github.com/prescottprue/react-redux-firebase) for clarity and to match other redux library naming conventions.
