### ISSUE TITLE
Uncaught TypeError: _firebase2.default is not a constructor

### ISSUE THREAD

**Issue by TheoMer** [prescottprue/redux-firebasev3#4]
OS: Windows 10 Pro
NPM: 3.9.5
Node: 
"firebase": "^3.2.1"
Project: ReactJs

So I'm receiving the above mentioned error message, and I've included both my reducers/index.js and store.js for review.

What am I missing here?

[index.txt](https://github.com/prescottprue/redux-firebasev3/files/415151/index.txt)
[store.txt](https://github.com/prescottprue/redux-firebasev3/files/415152/store.txt)

Note:
both files were renamed *.txt just to upload them.

**Comment by justinhandley** [comment]
I'm looking over your code, and I'm not sure that this is the issue, but just to rule it out, you are including redux-react-firebase in your code.  You've opened this ticket on redux-firebasev3.  Can you try to uninstall redux-react-firebase and install redux-firebasev3 and change the reference and confirm you are still getting this error?

**Comment by TheoMer** [comment]
@justinhandley That did the trick!

The confusion came from following the code in the 'Use' section, which still has the following defined:

`import {reduxReactFirebase, firebaseStateReducer} from 'redux-react-firebase'`

**Comment by prescottprue** [comment]
@justinhandley Great catch, thanks for helping out! @TheoMer will fix that in the use section today.

**Comment by prescottprue** [comment]
Updated the README with library name.
