### ISSUE TITLE
Performance problems when bound value changes rapidly

### ISSUE THREAD

**Issue by mrshll** [prescottprue/redux-firebasev3#40]
Say we bind to a db path `A`

`@firebaseConnect(['A'])`

If a child within `A` is appended to rapidly, I've noticed memory going > 1Gb and CPU stuck at 100%. 

![image](https://cloud.githubusercontent.com/assets/339996/18787209/d20f0658-816f-11e6-95b8-89409cfa51fe.png)

The page isn't doing anything dynamic. The only thing getting hit is the action to update `A`. `A` is getting updated a lot.

I'm thinking of adding a way to `fetch` but not `sync`. Anyone else find this happening?

**Comment by mrshll** [comment]
Or you know, I could also figure out the memory problem or throttle the realtime updates or something.

**Comment by mrshll** [comment]
And by rapidly I mean like, a write every few seconds. So not even that rapidly.

**Comment by prescottprue** [comment]
Hmmm... Interesting. Maybe a debounce setup is necessary? It would be nice to look at an example of this together, do you have a repo that I can view?

**Comment by mrshll** [comment]
Crap, sorry for not responding. I added a "once" type to my fork to get around this for now:

https://github.com/mmoutenot/redux-firebasev3

My example isn't open source, unfortunately :/

**Comment by prescottprue** [comment]
@mmoutenot Awesome, will check that out now.

**Comment by prescottprue** [comment]
What was your expected usage of once in the context of this library?

My thought was making it work like this:

``` js
@firebase([
  {type: 'once', path: '/todos'}
])
```

Compared to `on` which works like so:

``` js
@firebase([
   '/todos'
])
```

I got this working on the [`v0.1.7` branch](https://github.com/prescottprue/redux-firebasev3/tree/v0.1.7). Planning on releasing `v0.1.7` in the next few hours though, so let me know if you would like to see a different interface.

**Comment by mrshll** [comment]
Yeah, that is exactly how I am doing it. Turns out the api allows for types already, as seen in `createEvents`.

Cool! I'll start actually submitting PRs instead of making you copy stuff over from my branch. Thanks dude <3

**Comment by prescottprue** [comment]
@mmoutenot [`1.0.0` release](https://github.com/prescottprue/redux-firebasev3/releases/tag/v1.0.0) includes deboucing with settings available in config. This should fix your problem by default, but if not, it is a good place for us to start. Planning on updating the docs soon.

**Note:** The library has been renamed to [react-redux-firebase](https://github.com/prescottprue/react-redux-firebase) for clarity and to match other redux library naming conventions.

**Comment by mrshll** [comment]
Good stuff! Switching over to test with a bit of stress 💪
