### ISSUE TITLE
React Native configuration issue

### ISSUE THREAD

**Issue by tarkanlar** [prescottprue/redux-firebasev3#41]
@prescottprue  I really liked redux-firebasev3 but I couldnt make it work with react-native. I keep getting this error 
`FIREBASE FATAL ERROR Can't Determine firebase database URL`

Here are my store settings
https://gist.github.com/tarkanlar/c92b5dc30d2bab9b5682d65363cd409b

**Comment by prescottprue** [comment]
@tarkanlar Looking at it, and I will attempt to replicate.

**Comment by tarkanlar** [comment]
Thanks a lot @prescottprue, 
I can share my whole project if needed

**Comment by prescottprue** [comment]
@tarkanlar That would be ideal just so I can make sure it is solved.

**Comment by tarkanlar** [comment]
Perfect sending an email now.

**Comment by mrshll** [comment]
I use this in react + react-native projects, so I'm not sure the root problem is react-native. @tarkanlar happy to take a look at your project if you're cool with that and you want help, @prescottprue

**Comment by tarkanlar** [comment]
@mmoutenot Thanks, I shared the code with you. You probably got the email.

**Comment by mrshll** [comment]
This is just a guess, but I was able to get the app running without the error by providing the full configuration given by firebase. It's possible that by omitting the storageBucket, the firebase js lib is mistakenly throwing the "can't determine firebase database URL" (maybe someone forgot to update the string?).

Anyway, let's try this first before we dive deeper. And if this doesn't work, try creating a new project real quick and using that config. Maybe your old one's config has changed in some way?

```
export const fbConfig = {
  apiKey: "",
  authDomain: "",
  databaseURL: "",
  storageBucket: "",
  messagingSenderId: ""
};

export default {fbConfig};
```

**Comment by tarkanlar** [comment]
Thanks @mmoutenot  I didnt undrestand why, but it worked after I upgraded to 0.1.7
