### ISSUE TITLE
react-native support

### ISSUE THREAD

**Issue by 0xpbj** [prescottprue/redux-firebasev3#7]
Hi, will your library support react-native also? I am seeing the following error when I try to use this library:

> TransformError: /Users/prabhaav/Development/betaApp/node_modules/redux-firebasev3/build/index.js: Unknown plugin "transform-decorators-legacy" specified in "/Users/prabhaav/Development/betaApp/node_modules/redux-firebasev3/.babelrc" at 0, attempted to resolve relative to "/Users/prabhaav/Development/betaApp/node_modules/redux-firebasev3"

**Comment by prescottprue** [comment]
To the best of my knowledge, Firebase's web auth is not currently supported in React Native. Other than Auth, it should work, but I have yet to test it.

As for your error, it seems like your configuration is trying to build the library as part of your webpack build. It might help to use [webpack's module-noparse](https://webpack.github.io/docs/configuration.html#module-noparse), but I will need some way to replicate it to be sure. Is there a repo you can share me on to try to debug?

**Comment by 0xpbj** [comment]
@prescottprue I simply did the following steps:

npm install redux-firebasv3

in my reducer/index.js file

```

import {firebaseStateReducer} from 'redux-firebasev3'

const rootReducer = combineReducers({
  ...
  firebase: firebaseStateReducer
})
```

Here's my package.json:

``````
```
"firebase": "^3.2.0",
"firedux": "^0.6.6",
"react": "^15.3.0",
"react-native": "^0.31.0",
"react-redux": "^4.4.5",
"react-timer-mixin": "^0.13.3",
"redux": "^3.5.2",
"redux-firebasev3": "^0.1.0",
"redux-saga": "^0.11.0"
``````

```
```

**Comment by 0xpbj** [comment]
@prescottprue As for module-noparse, what is the best place to inject the following settings for a react-native project? : 

```
module: {
  loaders: [
    {
      test: /\.js$/,
      exclude: /(node_modules)/,
      loader: 'babel', // 'babel-loader' is also a legal name to reference
      query: {
        presets: ['es2015']
      }
    }
  ]
}
```

**Comment by prescottprue** [comment]
@prabhaav Make sure you have all of the code from the getting started:

``` js
import {createStore, combineReducers, compose} from 'redux'
import {reduxReactFirebase, firebaseStateReducer} from 'redux-firebasev3'

const rootReducer = combineReducers({
  firebase: firebaseStateReducer
})
const config = {
  apiKey: '<your-api-key>',
  authDomain: '<your-auth-domain>',
  databaseURL: '<your-database-url>',
  storageBucket: '<your-storage-bucket>'
}

// You seemed to have left this out of code you pasted in the issue
const createStoreWithFirebase = compose(
    reduxReactFirebase(config, { userProfile: 'users' }),
)(createStore)


const store = createStoreWithFirebase(rootReducer, initialState)
```

The noParse suggestion was not an attempt to fix your react-native question, but rather to try to fix the TransformError. Try adding this:

``` js
module: {
  noParse: /redux-firebasev3/
}
```

This is just a guess, but it might also help to create an alias to the built version of the library ( could throw a webpack warning):

``` js
resolve: {
  alias: {
    'redux-firebasev3': path.resolve(__dirname, 'node_modules/redux-firebasev3/build/index.js')
  }
}
```

**NOTE**: You will have to make the path match path relative to your config file and add `var path = require('path')` to make this work.

Again, **a repo or codepen to test these solutions on** is the only real way for me to provide a solution. I am not able to replicate these errors in repos I am using the library in currently. Provided a repo, it might be possible for me to create a PR with it working.

**Comment by 0xpbj** [comment]
@prescottprue Total noob mistake on my part. I am using npm packager and not webpack. Removing the .babelrc as recommended here (https://github.com/goatslacker/alt/issues/558) solved my issue. Hopefully, I won't run into more gotchas :)

**Comment by prescottprue** [comment]
@prabhaav Great, will go ahead and close this then. Let me know if there is anything I could make more clear in the docs to help a build config like yours.
